Repository devtron-labs/dashboard, pull requests merged in 2023-12, with the labels that each got.

#1502 feat: devtron loader
  package.json
  src/App.tsx
  src/components/ApplicationGroup/List/EnvironmentsList.tsx
  src/components/Jobs/JobList/JobsList.tsx
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/components/charts/list/DiscoverCharts.tsx
  src/components/common/navigation/NavigationRoutes.tsx
  src/components/v2/devtronStackManager/DevtronStackManager.tsx
  src/css/icons.scss
Labels: PR:Ready-to-Review

#1508 fix: Don't show deployment status card for EA mode
  src/components/app/details/appDetails/DeployedCommitCard.tsx
  src/components/app/details/appDetails/SourceInfo.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
Labels: PR:Ready-to-Review

#1465 feat: Add Resource Catalog for App Overview and replace AppStatus & processDeployedTime
  package.json
  src/assets/img/cluster-redirect.png
  src/components/ClusterNodes/ClusterNodeContainer.tsx
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/Jobs/Constants.ts
  src/components/Jobs/ExpandedRow/ExpandedRow.tsx
  src/components/Jobs/JobList/JobListView.tsx
  src/components/app/AppStatus.tsx
  src/components/app/Overview/EnvironmentList.tsx
  src/components/app/Overview/Overview.scss
  src/components/app/Overview/Overview.tsx
  src/components/app/Overview/constants.ts
  src/components/app/list-new/HelmAppList.tsx
  src/components/app/list/AppListView.tsx
  src/components/app/list/expandedRow/ExpandedRow.tsx
  src/components/app/types.ts
  src/components/charts/discoverChartDetail/ChartDeploymentList.tsx
  src/components/common/helpers/time.ts
  src/components/common/navigation/Navigation.tsx
  src/components/common/navigation/NavigationRoutes.tsx
  src/config/routes.ts
  src/css/base.scss
  src/css/formulae.scss
Labels: PR:Ready-to-Review

#1514 fix: ConfigMap Truncates for Long Integers
  src/components/CIPipelineN/CustomImageTags.tsx
  src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
Labels: PR:Ready-to-Review

#1484 feat: Protection config dev
  package.json
  src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
  src/components/EnvironmentOverride/EnvironmentOverride.tsx
  src/components/app/details/appConfig/AppComposeRouter.tsx
  src/components/common/helpers/Helpers.tsx
  src/css/base.scss
  src/css/icons.scss
Labels: PR:Ready-to-Review

#1516 fix:App group empty state handled
  src/components/ApplicationGroup/AppGroup.service.ts
Labels: PR:Ready-to-Review

#1485 fix:hover message and css fix
  src/components/app/details/appDetails/SourceInfo.tsx
  src/components/cluster/ClusterForm.tsx
Labels: PR:Ready-to-Review

#1493 fix: not able to change Authentication Type for Prometheus.
  src/components/cluster/Cluster.tsx
  src/components/cluster/ClusterForm.tsx
Labels: PR:Ready-to-Review

#1498 feat: add application dependencies
  src/components/app/Overview/Overview.tsx
  src/components/app/Overview/constants.ts
Labels: PR:Ready-to-Review

#1506 feat: Support for OCI registries in EA mode
  src/components/charts/list/ChartListPopUp.tsx
  src/components/common/Accordian/Accordian.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
  src/components/dockerRegistry/Docker.tsx
  src/components/dockerRegistry/dockerType.tsx
  src/components/globalConfigurations/GlobalConfiguration.tsx
  src/components/globalConfigurations/globalConfigurations.scss
  src/components/v2/appDetails/sourceInfo/EnvironmentSelector.component.tsx
  src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesEditor.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/config/constants.ts
  src/css/icons.scss
Labels: enhancement, PR:Ready-to-Review

#1519 feat: Global ConfigurationReplacement of Custom input & trim
  package.json
  src/components/ApplicationGroup/Details/TriggerView/BulkSourceChange.tsx
  src/components/CIPipelineN/CustomImageTags.tsx
  src/components/CIPipelineN/OutputDirectoryPath.tsx
  src/components/CIPipelineN/TaskDetailComponent.tsx
  src/components/CIPipelineN/TaskTypeDetailComponent.tsx
  src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
  src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
  src/components/apiTokens/CreateAPIToken.tsx
  src/components/apiTokens/EditAPIToken.tsx
  src/components/bulkEdits/BulkEdits.tsx
  src/components/chartRepo/ChartRepo.tsx
  src/components/ciConfig/CIConfigForm.tsx
  src/components/ciConfig/CIContainerRegistryConfig.tsx
  src/components/ciPipeline/SourceMaterials.tsx
  src/components/cluster/ClusterForm.tsx
  src/components/cluster/Environment.tsx
  src/components/common/formFields/CustomInput.tsx
  src/components/common/formFields/customInput.css
  src/components/common/helpers/Helpers.tsx
  src/components/common/index.ts
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateGUIView.tsx
  src/components/dockerRegistry/Docker.tsx
  src/components/externalLinks/ExternalLinksCRUD/ConfigureLinkAction.tsx
  src/components/gitOps/GitOpsConfiguration.tsx
  src/components/gitOps/constants.ts
  src/components/gitProvider/GitProvider.tsx
  src/components/globalConfigurations/GlobalConfiguration.tsx
  src/components/globalConfigurations/globalConfiguration.type.ts
  src/components/hostURL/HostURL.tsx
  src/components/login/SSOLogin.tsx
  src/components/material/CreateMaterial.tsx
  src/components/material/MaterialView.tsx
  src/components/material/UpdateMaterial.tsx
  src/components/material/material.types.ts
  src/components/project/Project.tsx
  src/components/project/ProjectList.tsx
  src/components/util/KeyValueFileInput.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/EphemeralContainerDrawer.tsx
  src/css/base.scss
Labels: PR:Issue-verification-failed

#1497 feat: cm based show/hide default_cluster
  .env
  src/components/ClusterNodes/ClusterSelectionList.tsx
  src/components/ResourceBrowser/ResourceList/ClusterSelector.tsx
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/index.tsx
Labels: PR:Ready-to-Review

#1527 feat: Revert of app config branch changes
  package.json
  src/components/ApplicationGroup/Details/TriggerView/BulkSourceChange.tsx
  src/components/CIPipelineN/CustomImageTags.tsx
  src/components/apiTokens/CreateAPIToken.tsx
  src/components/bulkEdits/BulkEdits.tsx
  src/components/chartRepo/ChartRepo.tsx
  src/components/cluster/ClusterForm.tsx
  src/components/cluster/Environment.tsx
  src/components/common/formFields/CustomInput.tsx
  src/components/common/helpers/Helpers.tsx
  src/components/dockerRegistry/Docker.tsx
  src/components/gitOps/GitOpsConfiguration.tsx
  src/components/gitOps/constants.ts
  src/components/gitProvider/GitProvider.tsx
  src/components/globalConfigurations/GlobalConfiguration.tsx
  src/components/globalConfigurations/globalConfiguration.type.ts
  src/components/hostURL/HostURL.tsx
  src/components/login/SSOLogin.tsx
  src/components/material/MaterialView.tsx
  src/components/project/Project.tsx
  src/components/project/ProjectList.tsx
  src/css/base.scss
Labels: PR:Issue-verification-failed

#1526 feat: custom input > App configuration
  package.json
  src/components/CIPipelineN/CustomImageTags.tsx
  src/components/CIPipelineN/OutputDirectoryPath.tsx
  src/components/CIPipelineN/TaskDetailComponent.tsx
  src/components/CIPipelineN/TaskTypeDetailComponent.tsx
  src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
  src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
  src/components/apiTokens/EditAPIToken.tsx
  src/components/ciConfig/CIConfigForm.tsx
  src/components/ciConfig/CIContainerRegistryConfig.tsx
  src/components/ciPipeline/SourceMaterials.tsx
  src/components/common/formFields/CustomInput.tsx
  src/components/common/formFields/customInput.css
  src/components/common/index.ts
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateGUIView.tsx
  src/components/dockerRegistry/Docker.tsx
  src/components/externalLinks/ExternalLinksCRUD/ConfigureLinkAction.tsx
  src/components/globalConfigurations/GlobalConfiguration.tsx
  src/components/material/MaterialView.tsx
  src/components/util/KeyValueFileInput.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/EphemeralContainerDrawer.tsx
  src/css/base.scss
Labels: PR:Issue-verification-failed

#1529 feat: Custom input bug fixes
  src/components/CIPipelineN/Build.tsx
  src/components/app/details/triggerView/BranchRegexModal.tsx
  src/components/cdPipeline/BuildCD.tsx
  src/components/cdPipeline/CDPipeline.tsx
  src/components/ciConfig/CICreateDockerfileOption.tsx
  src/components/ciConfig/CIDockerFileConfig.tsx
  src/components/ciPipeline/LinkedCIPipelineEdit.tsx
  src/components/ciPipeline/LinkedCIPipelineView.tsx
  src/components/ciPipeline/WebhookSelectorCondition.tsx
  src/config/constantMessaging.ts
  src/css/base.scss
Labels: PR:Issue-verification-failed

#1535 fix: Missing source data in Webhook
  src/components/app/details/cicdHistory/History.components.tsx
Labels: PR:Ready-to-Review

#1476 feat: pod link to worker
  src/components/app/details/appDetails/appDetails.scss
  src/components/app/details/cIDetails/CIDetails.tsx
  src/components/app/details/cicdHistory/Constants.ts
  src/components/app/details/cicdHistory/TriggerDetails.tsx
  src/components/app/details/cicdHistory/types.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
Labels: PR:Ready-to-Review

#1513 feat: add the catalog framework under global configuration
  src/components/globalConfigurations/GlobalConfiguration.tsx
  src/config/routes.ts
  src/css/base.scss
Labels: PR:Ready-to-Review

#1532 feat: force abort build ci
  src/components/app/details/cicdHistory/TriggerDetails.tsx
  src/components/app/service.ts
Labels: PR:Issue-verification-failed

#1540 fix: css nopod
  src/components/app/ResourceTreeNodes.tsx
  src/components/app/details/appDetails/appDetails.scss
Labels: PR:Ready-to-Review

#1538 fix: node overlap hidden by calculating maxDepth
  src/components/app/details/triggerView/types.ts
  src/components/app/details/triggerView/workflow.service.ts
Labels: PR:Issue-verification-failed

#1544 feat: Updated version for Custom Input
  package.json
  src/components/gitOps/GitOpsConfiguration.tsx
Labels: PR:Ready-to-Review

#1542 fix: Not able to go back from app list page
  src/components/common/navigation/NavigationRoutes.tsx
Labels: PR:Ready-to-Review

#1547 fix: missing GCR list in Registry Providers
  src/components/dockerRegistry/Docker.tsx
Labels: PR:Ready-to-Review

#1549 fix: missing labels due to missing callback
  src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
  src/components/cluster/ClusterForm.tsx
  src/components/material/MaterialView.tsx
  src/components/notifications/SESConfigModal.tsx
Labels: PR:Ready-to-Review

#1523 feat: add delete cd
  package.json
  src/components/ApplicationGroup/AppGroup.service.ts
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/Details/EnvCIDetails/EnvCIDetails.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/details/appConfig/AppComposeRouter.tsx
  src/components/app/details/cIDetails/CIDetails.tsx
  src/components/app/details/triggerView/config.ts
  src/components/app/details/triggerView/types.ts
  src/components/app/details/triggerView/workflow.service.ts
  src/components/app/details/triggerView/workflow/Workflow.tsx
  src/components/cdPipeline/CDPipeline.tsx
  src/components/cdPipeline/DeleteCDNode.tsx
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/cdPipeline/types.ts
  src/components/common/edge/rectangularEdge.tsx
  src/components/workflowEditor/PipelineSelect.tsx
  src/components/workflowEditor/ToggleCDSelectButton.tsx
  src/components/workflowEditor/Workflow.tsx
  src/components/workflowEditor/WorkflowOptionsModal.tsx
  src/components/workflowEditor/nodes/CDNode.tsx
  src/components/workflowEditor/nodes/CINode.tsx
  src/components/workflowEditor/nodes/WebhookNode.tsx
  src/components/workflowEditor/types.ts
  src/components/workflowEditor/workflowEditor.constants.ts
  src/components/workflowEditor/workflowEditor.tsx
  src/css/base.scss
  src/css/colorPalette.scss
  src/css/workflow.scss
Labels: PR:Ready-to-Review

#1522 fix: GA and Qa bugs in app-dependency
  src/components/app/Overview/Overview.tsx
Labels: PR:Ready-to-Review

#1554 fix: Label for webhook token
  src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
  src/components/deploymentGroups/BulkActionEdit.tsx
  src/components/material/MaterialView.tsx
  src/css/base.scss
Labels: PR:Ready-to-Review

#1520 fix: state resetting to default in cipipeline
  src/components/CIPipelineN/AdvancedConfigOptions.tsx
  src/components/CIPipelineN/Build.tsx
  src/components/CIPipelineN/CIPipeline.tsx
  src/components/ciConfig/types.tsx
  src/components/ciPipeline/types.ts
Labels: PR:Ready-to-Review

#1552 fix: worker pod link
  src/components/app/details/cIDetails/CIDetails.tsx
  src/components/app/details/cicdHistory/TriggerDetails.tsx
  src/components/app/details/cicdHistory/types.tsx
  src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
Labels: PR:Ready-to-Review

#1534 feat: Diff modal for base deployment and deployment template
  package.json
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
  src/components/ApplicationGroup/Details/EnvironmentConfig/EnvConfig.tsx
  src/components/CodeEditor/CodeEditor.tsx
  src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
  src/components/EnvironmentOverride/EnvironmentOverride.tsx
  src/components/EnvironmentOverride/EnvironmentOverrides.type.ts
  src/components/EnvironmentOverride/service.ts
  src/components/app/details/appConfig/AppComposeRouter.tsx
  src/components/app/details/appConfig/AppConfig.tsx
  src/components/app/details/appConfig/appConfig.type.ts
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/deploymentConfig/DeploymentConfig.utils.ts
  src/components/deploymentConfig/DeploymentConfigReducer.ts
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateView.component.tsx
  src/components/deploymentConfig/deploymentConfig.scss
  src/components/deploymentConfig/service.tsx
  src/components/deploymentConfig/types.tsx
  src/config/constants.ts
Labels: PR:Issue-verification-failed

#1517 feat: add argo cd tile in deployment status steps
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/appDetails/DeploymentStatusBreakdown.tsx
  src/components/app/details/appDetails/DeploymentStatusCard.tsx
  src/components/app/details/appDetails/DeploymentStatusDetailModal.tsx
  src/components/app/details/appDetails/DeploymentStatusDetailRow.tsx
  src/components/app/details/appDetails/appDetails.type.ts
  src/components/app/details/appDetails/utils.tsx
  src/components/v2/appDetails/AppDetails.component.tsx
  src/config/constants.ts
Labels: PR:Ready-to-Review

#1562 fix: wrong chart name
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
Labels: PR:Ready-to-Review
