Repository devtron-labs/dashboard, pull requests merged in 2023-11, with the labels that each got.

#1425 feat: Custom tag v2 build trigger
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/service.ts
  src/css/base.scss
Labels: PR:Issue-verification-failed

#1438 deployment history message truncate
  src/components/app/details/cicdHistory/TriggerDetails.tsx
Labels: enhancement

#1401 fix: Changes to persist cluster terminal session even on tab switches
  src/components/ClusterNodes/ClusterSelectionList.tsx
  src/components/ClusterNodes/ClusterTerminal.tsx
  src/components/ClusterNodes/clusterNodes.scss
  src/components/ClusterNodes/types.ts
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/components/ResourceBrowser/Types.ts
  src/components/cluster/cluster.type.ts
  src/components/cluster/cluster.util.ts
  src/components/common/DynamicTabs/useTabs.ts
  src/components/common/helpers/Helpers.tsx
  src/components/v2/appDetails/appDetails.type.ts
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Terminal.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
Labels: PR:Ready-to-Review

#1439 fix: Persist cluster terminal logs on switching back from pod terminal
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
Labels: PR:Ready-to-Review

#1369 fix: stable dt19 v3 + v4
  package.json
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/CIPipelineN/CIPipeline.tsx
  src/components/CIPipelineN/ciPipeline.utils.ts
  src/components/ConfigMapSecret/ConfigMapSecretDataEditorContainer.tsx
  src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
  src/components/app/config.tsx
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/appDetails/appDetails.type.ts
  src/components/app/details/cicdHistory/Artifacts.tsx
  src/components/app/details/cicdHistory/History.components.tsx
  src/components/app/details/cicdHistory/types.tsx
  src/components/app/details/main.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/details/triggerView/ciMaterial.tsx
  src/components/app/details/triggerView/types.ts
  src/components/app/details/triggerView/workflow.service.ts
  src/components/app/details/triggerView/workflow/Workflow.tsx
  src/components/app/list-new/AppList.tsx
  src/components/app/list-new/HelmAppList.tsx
  src/components/app/service.ts
  src/components/cdPipeline/validationRules.ts
  src/components/ciConfig/CIConfigForm.tsx
  src/components/common/GitInfoMaterial.tsx
  src/components/common/helpers/git.ts
  src/components/common/helpers/workflowURL.ts
  src/components/dockerRegistry/Docker.tsx
  src/components/v2/appDetails/AppDetails.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
  src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/components/workflowEditor/Workflow.tsx
  src/components/workflowEditor/workflowEditor.tsx
  src/config/constantMessaging.ts
  src/config/constants.ts
Labels: PR:Ready-to-Review

#1417 feat: scoped var support in cm/cs
  src/components/ConfigMapSecret/ConfigMap/ConfigMapList.tsx
  src/components/ConfigMapSecret/ConfigMapSecret.scss
  src/components/ConfigMapSecret/Secret/SecretList.tsx
  src/components/ConfigMapSecret/Types.ts
  src/components/EnvironmentOverride/EnvironmentOverride.tsx
  src/components/app/details/cdDetails/cd.type.ts
  src/components/app/details/cdDetails/deploymentHistoryDiff/DeploymentHistoryDiffView.tsx
  src/components/app/details/cdDetails/service.ts
  src/components/app/details/triggerView/triggerViewConfigDiff/TriggerViewConfigDiff.tsx
Labels: PR:Ready-to-Review

#1443 fix: cd materials rbac
  package.json
  src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
Labels: PR:Issue-verification-failed

#1413 feat: Overview Tab UI Revamp for Devtron App, Helm App, Cluster and Job
  package.json
  public/index.html
  src/assets/icons/cluster-overview.svg
  src/assets/icons/ic-activity.svg
  src/assets/icons/ic-world-black.svg
  src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/ClusterNodes/clusterNodes.scss
  src/components/ClusterNodes/clusterNodes.service.tsx
  src/components/ClusterNodes/constants.ts
  src/components/ClusterNodes/types.ts
  src/components/Jobs/JobDetails/JobDetails.tsx
  src/components/ResourceBrowser/Constants.ts
  src/components/ResourceBrowser/ResourceList/ConnectingToClusterState.tsx
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/components/ResourceBrowser/ResourceList/Sidebar.tsx
  src/components/ResourceBrowser/Utils.ts
  src/components/app/AppStatus.tsx
  src/components/app/Overview/EnvironmentList.tsx
  src/components/app/Overview/Overview.scss
  src/components/app/Overview/Overview.tsx
  src/components/app/Overview/TagChipsContainer.tsx
  src/components/app/Overview/constants.ts
  src/components/app/Overview/utils.tsx
  src/components/app/create/CreateApp.tsx
  src/components/app/create/validationRules.ts
  src/components/app/details/AboutAppInfoModal.tsx
  src/components/app/details/AboutTagEditModal.tsx
  src/components/app/details/cdDetails/CDDetails.tsx
  src/components/app/details/main.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/list-new/Constants.ts
  src/components/app/service.ts
  src/components/app/types.ts
  src/components/common/Description/GenericDescription.tsx
  src/components/common/DynamicTabs/useTabs.ts
  src/components/common/EditableTextArea/EditableTextArea.tsx
  src/components/common/EditableTextArea/types.ts
  src/components/common/index.ts
  src/components/v2/HelmAppOverview/HelpAppOverview.tsx
  src/components/v2/appDetails/appDetails.store.ts
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
  src/components/v2/headers/ChartHeader.component.tsx
  src/components/v2/index.tsx
  src/config/constantMessaging.ts
  src/config/constants.ts
  src/css/base.scss
  src/css/formulae.scss
  src/services/service.types.ts
Labels: PR:Ready-to-Review

#1449 fix: trigger-info drawer responsiveness
  src/components/app/list/TriggerInfo.tsx
  src/css/triggerView.scss
Labels: PR:Ready-to-Review

#1457 fix: pod terminal tab getting stuck
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
Labels: PR:Ready-to-Review

#1458 fix: Auto trim https:// or oci:// in registry URL
  src/components/dockerRegistry/Docker.tsx
Labels: PR:Ready-to-Review

#1455 feat: Announcement Banner
  .env
  src/assets/icons/ic-megaphone.svg
  src/components/ApplicationGroup/List/EnvironmentsList.tsx
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/app/details/AppHeader.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/common/AnnouncementBanner.tsx
  src/components/common/header/PageHeader.tsx
  src/components/common/header/header.type.ts
  src/components/common/navigation/NavigationRoutes.tsx
  src/components/dockerRegistry/Docker.tsx
  src/components/v2/headers/AppHeader.component.tsx
  src/components/v2/headers/ChartHeader.component.tsx
  src/components/v2/headers/EAHeader.component.tsx
  src/css/base.scss
  src/index.tsx
Labels: PR:Ready-to-Review

#1424 fix: Sorting event data based on the lastTimeStamp
  src/components/ClusterNodes/ClusterEvents.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Events.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/EventsTable.tsx
Labels: PR:Ready-to-Review

#1454 feat: add catalog
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/app/Overview/Overview.tsx
  src/components/common/navigation/Navigation.tsx
  src/components/common/navigation/NavigationRoutes.tsx
Labels: PR:Issue-verification-failed

#1463 feat: add dependency tab on app overview
  package.json
  src/components/app/Overview/EnvironmentList.tsx
  src/components/app/Overview/Overview.tsx
  src/config/constants.ts
Labels: PR:Issue-verification-failed

#1467 feat: update overview tabs using search params
  src/components/app/Overview/Overview.tsx
  src/components/app/Overview/constants.ts
  src/config/constants.ts
Labels: PR:Ready-to-Review

#1440 feat: added redirection for config map secret
  src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
  src/components/EnvironmentOverride/EnvironmentOverride.tsx
  src/components/app/details/appConfig/AppComposeRouter.tsx
Labels: PR:Issue-verification-failed

#1462 fix: Devtron Apps break if default chart repo is deleted
  src/components/ClusterNodes/clusterNodes.scss
  src/components/chartRepo/ChartRepo.tsx
  src/components/charts/list/ChartListPopUp.tsx
  src/components/common/navigation/Navigation.tsx
  src/components/common/navigation/NavigationRoutes.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
Labels: PR:Ready-to-Review

#1469 fix: change default opt
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/components/v2/appDetails/k8Resource/NodeTreeTabList.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.util.ts
Labels: PR:Ready-to-Review

#1473 feat: Login page BG from CM
  .env
  config.md
  src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx
  src/components/login/Login.tsx
  src/index.tsx
Labels: PR:Ready-to-Review

#1428 fix: cd materials architecture
  package.json
  src/assets/icons/ic-info-filled-lg.svg
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/details/cdDetails/CDDetails.tsx
  src/components/app/details/cdDetails/service.ts
  src/components/app/details/cicdHistory/Artifacts.tsx
  src/components/app/details/cicdHistory/History.components.tsx
  src/components/app/details/cicdHistory/types.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/details/triggerView/cdMaterials.utils.ts
  src/components/app/details/triggerView/config.ts
  src/components/app/details/triggerView/types.ts
  src/components/app/details/triggerView/workflow.service.ts
  src/components/app/service.ts
  src/components/common/security/ScannedByToolModal.tsx
  src/components/deploymentGroups/BulkActionDetails.tsx
  src/components/deploymentGroups/DeploymentGroupList.tsx
  src/css/base.scss
Labels: PR:Ready-to-Review

#1451 feat: customize ui for array, object and field error templates
  src/components/common/RJSF/Form.tsx
  src/components/common/RJSF/common/FieldRow.tsx
  src/components/common/RJSF/common/types.ts
  src/components/common/RJSF/config.ts
  src/components/common/RJSF/constants.ts
  src/components/common/RJSF/rjsfForm.scss
  src/components/common/RJSF/templates/ArrayFieldItemTemplate.tsx
  src/components/common/RJSF/templates/ArrayFieldTemplate.tsx
  src/components/common/RJSF/templates/BaseInput.tsx
  src/components/common/RJSF/templates/ButtonTemplates/AddButton.tsx
  src/components/common/RJSF/templates/ButtonTemplates/RemoveButton.tsx
  src/components/common/RJSF/templates/ButtonTemplates/SubmitButton.tsx
  src/components/common/RJSF/templates/ButtonTemplates/index.ts
  src/components/common/RJSF/templates/Description.tsx
  src/components/common/RJSF/templates/Field.tsx
  src/components/common/RJSF/templates/FieldErrorTemplate.tsx
  src/components/common/RJSF/templates/ObjectFieldTemplate.tsx
  src/components/common/RJSF/templates/WrapIfAdditionalTemplate.tsx
  src/components/common/RJSF/templates/index.ts
  src/components/common/RJSF/types.ts
  src/components/common/RJSF/utils.ts
  src/components/common/RJSF/widgets/Select.tsx
  src/css/base.scss
  src/css/formulae.scss
  src/message.json
  src/schema.json
Labels: PR:Issue-verification-failed

#1426 feat: Custom tag v2
  package.json
  src/components/CIPipelineN/AdvancedConfigOptions.tsx
  src/components/CIPipelineN/Build.tsx
  src/components/CIPipelineN/CIPipeline.tsx
  src/components/CIPipelineN/CustomImageTag.type.ts
  src/components/CIPipelineN/CustomImageTags.tsx
  src/components/CIPipelineN/ciPipeline.utils.ts
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/cdPipeline/BuildCD.tsx
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/ciConfig/types.tsx
  src/components/ciPipeline/ciPipeline.scss
  src/components/ciPipeline/ciPipeline.service.ts
  src/components/ciPipeline/types.ts
  src/components/workflowEditor/types.ts
  src/css/base.scss
  src/index.tsx
Labels: PR:Ready-to-Review

#1380 feat: handled additional deployment states
  src/assets/icons/ic-clock.svg
  src/components/app/config.tsx
  src/components/app/details/appDetails/DeploymentStatusCard.tsx
  src/components/app/details/appDetails/appDetails.scss
  src/components/app/details/cicdHistory/TriggerDetails.tsx
  src/components/app/details/cicdHistory/types.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/environmentStatus.scss
  src/config/constants.ts
  src/css/base.scss
  src/css/icons.scss
Labels: enhancement, PR:Ready-to-Review

#1480 chore: use AppStatus and processDeployedTime from common lib
  src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
  src/components/Jobs/Constants.ts
  src/components/Jobs/ExpandedRow/ExpandedRow.tsx
  src/components/Jobs/JobList/JobListView.tsx
  src/components/app/AppStatus.tsx
  src/components/app/Overview/EnvironmentList.tsx
  src/components/app/list-new/HelmAppList.tsx
  src/components/app/list/AppListView.tsx
  src/components/app/list/expandedRow/ExpandedRow.tsx
  src/components/app/types.ts
  src/components/charts/discoverChartDetail/ChartDeploymentList.tsx
  src/components/common/helpers/time.ts
Labels: PR:Ready-to-Review

#1491 fix: style for scoped variable tippy
  src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx
Labels: PR:Ready-to-Review

#1481 feat: ui revamp and hibernate/unhibernate option in AppGroup
  src/assets/icons/ic-grid-view-blue.svg
  src/assets/icons/ic-hibernate-3.svg
  src/assets/icons/ic-medium-hibernate.svg
  src/assets/icons/ic-medium-unhibernate.svg
  src/assets/icons/ic-unhibernate.svg
  src/components/ApplicationGroup/AppGroup.service.ts
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/AppGroupAppFilter.components.tsx
  src/components/ApplicationGroup/AppGroupAppFilter.tsx
  src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
  src/components/ApplicationGroup/Constants.ts
  src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusListDrawer.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusRow.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/constants.ts
  src/components/ApplicationGroup/Details/EnvironmentOverview/envOverview.scss
  src/components/ApplicationGroup/Details/EnvironmentOverview/service.ts
  src/components/app/Overview/Overview.tsx
  src/components/app/types.ts
  src/css/base.scss
  src/css/forms.scss
Labels: PR:Ready-to-Review

#1453 feat: app details cards devtron & helm apps
  src/assets/icons/ic-clock-counterclockwise.svg
  src/assets/icons/ic-secure.svg
  src/components/Jobs/JobList/JobListView.tsx
  src/components/app/details/appConfig/EnvironmentOverrideRouter.tsx
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/appDetails/AppMetrics.tsx
  src/components/app/details/appDetails/AppStatusCard.tsx
  src/components/app/details/appDetails/DeployedCommitCard.tsx
  src/components/app/details/appDetails/DeploymentStatusCard.tsx
  src/components/app/details/appDetails/IssuesCard.tsx
  src/components/app/details/appDetails/IssuesListingModal.tsx
  src/components/app/details/appDetails/LastUpdatedCard.tsx
  src/components/app/details/appDetails/LoadingCard.tsx
  src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx
  src/components/app/details/appDetails/SourceInfo.tsx
  src/components/app/details/appDetails/appDetails.scss
  src/components/app/details/appDetails/appDetails.type.ts
  src/components/app/details/appDetails/utils.tsx
  src/components/app/list/AppListView.tsx
  src/components/app/types.ts
  src/components/v2/appDetails/AppDetails.component.tsx
  src/components/v2/appDetails/appDetails.scss
  src/components/v2/appDetails/appDetails.type.ts
  src/components/v2/appDetails/k8Resource/NodeTreeTabList.scss
  src/components/v2/appDetails/sourceInfo/environment.type.ts
  src/components/v2/appDetails/sourceInfo/environmentStatus/ChartUsedCard.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/HelmAppConfigApplyStatusCard.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/environmentStatus.scss
  src/css/base.scss
  src/css/forms.scss
Labels: PR:Ready-to-Review

#1499 fix: env id issues on switching tabs on Applications page
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/appDetails/utils.tsx
Labels: PR:Ready-to-Review

#1507 fix: css checkbox fix
  src/css/forms.scss
Labels: PR:Ready-to-Review
