Repository devtron-labs/dashboard, pull requests merged in 2023-09, with the labels that each got.

#1223 feat: custom chart download
  package.json
  src/assets/icons/ic-upload.svg
  src/components/CustomChart/CustomChartList.tsx
  src/components/CustomChart/CustomChartList.utils.ts
  src/components/CustomChart/UploadChartModal.tsx
  src/components/CustomChart/__mocks__/CustomChartList.mock.ts
  src/components/CustomChart/__test__/CustomChartList.test.tsx
  src/components/CustomChart/customChart.scss
  src/components/CustomChart/types.ts
  src/components/EnvironmentOverride/EnvironmentOverride.tsx
  src/components/globalConfigurations/globalConfigurations.scss
  src/config/constants.ts
  src/css/base.scss
  yarn.lock
Labels: enhancement

#1266 fix: configure page of external helm app is breaking
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
Labels: enhancement

#1275 feat: added validation for empty yaml
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.constants.ts
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
Labels: enhancement

#1295 fix: reset pod counts in case of hibernate
  src/components/v2/appDetails/k8Resource/nodeType/PodHeader.component.tsx
Labels: enhancement

#1289 fixed: Pre CD Logs page fluctuating
  src/components/app/details/cdDetails/CDDetails.tsx
Labels: enhancement

#1247 feat: handled release status for helm installed charts
  src/components/app/details/appDetails/utils.tsx
  src/components/external-apps/ExternalAppService.ts
  src/components/v2/appDetails/AppDetails.component.tsx
  src/components/v2/appDetails/ReleaseStatusEmptyState.tsx
  src/components/v2/appDetails/appDetails.type.ts
  src/components/v2/appDetails/ea/EAAppDetail.component.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/HelmAppConfigApplyStatusCard.tsx
  src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
  src/components/v2/index.tsx
  src/config/constants.ts
  src/css/base.scss
Labels: enhancement

#1312 chore: code formatting
  src/components/common/DeploymentTypeIcon/DeploymentTypeIcon.tsx
Labels: enhancement

#1314 feat: removed unnecessary virtual filter from API response
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
Labels: enhancement

#1250 chore: create pr-issue-validator
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#1310 feat: Ability to change branch for all selected applications during bulk build from Application Groups
  src/components/ApplicationGroup/Constants.ts
  src/components/ApplicationGroup/Details/TriggerView/BulkSourceChange.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.scss
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/ApplicationGroup/Details/TriggerView/SourceUpdateResponseModal.tsx
  src/components/app/details/triggerView/ciMaterial.tsx
  src/components/app/service.ts
  src/config/constants.ts
Labels: PR:Issue-verification-failed

#1315 fix: DT19 bug fixes V1
  src/components/ClusterNodes/ClusterSelectionList.tsx
  src/components/CodeEditor/CodeEditor.tsx
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/components/ResourceBrowser/Utils.ts
  src/components/apiTokens/authorization.utils.ts
  src/components/app/Overview/Overview.tsx
  src/components/app/details/appConfig/appConfig.scss
  src/components/app/list-new/AppList.tsx
  src/components/app/list-new/HelmAppList.tsx
  src/components/app/types.ts
  src/components/cdPipeline/BuildCD.tsx
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/charts/ChartGroupUpdate.tsx
  src/components/common/ClusterNotReachableDailog/ClusterNotReachableDialog.tsx
  src/components/common/DeploymentTypeIcon/DeploymentTypeIcon.tsx
  src/components/common/Description/GenericDescription.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
  src/components/login/SSOLogin.tsx
  src/components/login/ssoConfig.types.tsx
  src/components/security/SecurityPolicyEdit.tsx
  src/components/userGroups/User.tsx
  src/components/userGroups/userGroups.types.ts
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
  src/components/v2/appDetails/k8Resource/nodeType/PodHeader.component.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.constants.ts
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/components/workflowEditor/types.ts
  src/components/workflowEditor/workflowEditor.tsx
  src/config/constants.ts
Labels: enhancement, PR:Issue-verification-failed

#1325 fix: oci public validation for Azure & Quay
  src/components/dockerRegistry/Docker.tsx
Labels: PR:Issue-verification-failed

#1330 fix: Slash validator
  src/components/dockerRegistry/Docker.tsx
Labels: PR:Issue-verification-failed

#1335 fix: revert fixes
  src/components/ClusterNodes/ClusterSelectionList.tsx
  src/components/app/details/appConfig/appConfig.scss
  src/components/app/list-new/HelmAppList.tsx
Labels: PR:Issue-verification-failed

#1306 feat: use scoped variables
  package.json
  src/assets/icons/ic-variable.svg
  src/components/CIPipelineN/CIPipeline.tsx
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/cdPipeline/cdPipeline.service.ts
  src/components/cdPipeline/cdPipeline.types.ts
  src/components/common/ClipboardButton/ClipboardButton.tsx
  src/components/common/ClipboardButton/__tests__/ClipboardButton.test.tsx
  src/components/common/ClipboardButton/types.ts
  src/components/common/FloatingVariablesSuggestions/FloatingVariablesSuggestions.tsx
  src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx
  src/components/common/FloatingVariablesSuggestions/Suggestions.tsx
  src/components/common/FloatingVariablesSuggestions/SuggestionsInfo.tsx
  src/components/common/FloatingVariablesSuggestions/__tests__/FloatingVariablesSuggestions.test.tsx
  src/components/common/FloatingVariablesSuggestions/__tests__/Suggestions.test.tsx
  src/components/common/FloatingVariablesSuggestions/__tests__/SuggestionsInfo.test.tsx
  src/components/common/FloatingVariablesSuggestions/__tests__/SuggestionsItem.test.tsx
  src/components/common/FloatingVariablesSuggestions/__tests__/service.test.ts
  src/components/common/FloatingVariablesSuggestions/constants.ts
  src/components/common/FloatingVariablesSuggestions/mocks.ts
  src/components/common/FloatingVariablesSuggestions/service.ts
  src/components/common/FloatingVariablesSuggestions/types.ts
  src/components/common/Grid/Grid.tsx
  src/components/common/Grid/types.ts
  src/components/common/formFields/ButtonWithLoader.tsx
  src/components/common/helpers/Helpers.tsx
  src/components/common/index.ts
  src/components/scopedVariables/VariablesList.tsx
  src/components/scopedVariables/__tests__/SavedVariables.test.tsx
  src/components/workflowEditor/workflowEditor.scss
  src/css/base.scss
  src/css/icons.scss
Labels: enhancement, PR:Issue-verification-failed

#1337 fix: add package json for fe-common lib
  package.json
Labels: PR:Issue-verification-failed

#1341 chore: Update pr-issue-validator
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#1324 feat: Added support for job type CI
  .env
  package.json
  src/components/ApplicationGroup/Details/EnvCIDetails/EnvCIDetails.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/CIPipelineN/CIPipeline.tsx
  src/components/CIPipelineN/Sidebar.tsx
  src/components/app/details/cIDetails/CIDetails.tsx
  src/components/app/details/cIDetails/types.tsx
  src/components/app/details/cicdHistory/Artifacts.tsx
  src/components/app/details/cicdHistory/Sidebar.tsx
  src/components/app/details/cicdHistory/TriggerDetails.tsx
  src/components/app/details/cicdHistory/types.tsx
  src/components/app/details/triggerView/CiWebhookDebuggingModal.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/types.ts
  src/components/app/details/triggerView/workflow.service.ts
  src/components/app/details/triggerView/workflow/Workflow.tsx
  src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
  src/components/ciConfig/types.tsx
  src/components/ciPipeline/LinkedCIPipelineEdit.tsx
  src/components/ciPipeline/LinkedCIPipelineView.tsx
  src/components/ciPipeline/types.ts
  src/components/common/GitInfoMaterial.tsx
  src/components/common/helpers/workflowURL.ts
  src/components/workflowEditor/PipelineSelect.tsx
  src/components/workflowEditor/Workflow.tsx
  src/components/workflowEditor/nodes/CINode.tsx
  src/components/workflowEditor/workflowEditor.tsx
  src/config/constantMessaging.ts
  src/config/routes.ts
  src/css/base.scss
  src/index.tsx
  yarn.lock
Labels: enhancement, PR:Issue-verification-failed

#1338 feat: global config
  package.json
  src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/ClusterNodes/ClusterSelectionList.tsx
  src/components/app/details/triggerView/Constants.ts
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/details/triggerView/types.ts
  src/components/app/service.ts
  src/components/globalConfigurations/GlobalConfiguration.tsx
  src/config/routes.ts
  src/util/Subject.ts
Labels: PR:Ready-to-Review

#1316 Feat: search & refresh deployments
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/details/triggerView/types.ts
Labels: PR:Issue-verification-failed

#1339 feat: App env filter
  src/components/ApplicationGroup/AppGroup.service.ts
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/AppGroupAppFilter.components.tsx
  src/components/ApplicationGroup/AppGroupAppFilter.tsx
  src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
  src/components/ApplicationGroup/Constants.ts
  src/components/ApplicationGroup/CreateAppGroup.tsx
  src/components/EnvironmentOverride/EnvironmentOverride.tsx
  src/components/app/Overview/Overview.tsx
  src/components/app/details/AppHeader.tsx
  src/components/app/details/app.scss
  src/components/app/details/appConfig/AppComposeRouter.tsx
  src/components/app/details/appConfig/AppConfig.tsx
  src/components/app/details/appConfig/EnvironmentOverrideRouter.tsx
  src/components/app/details/appConfig/appConfig.type.ts
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/cIDetails/CIDetails.tsx
  src/components/app/details/cdDetails/CDDetails.tsx
  src/components/app/details/main.tsx
  src/components/app/details/metrics/DeploymentMetrics.tsx
  src/components/app/details/metrics/deploymentMetrics.types.ts
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/types.ts
  src/components/app/details/triggerView/workflow.service.ts
  src/components/app/service.ts
  src/components/app/types.ts
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/workflowEditor/Workflow.tsx
  src/components/workflowEditor/nodes/CDNode.tsx
  src/components/workflowEditor/nodes/CINode.tsx
  src/components/workflowEditor/nodes/WebhookNode.tsx
  src/components/workflowEditor/types.ts
  src/components/workflowEditor/workflowEditor.tsx
  src/css/base.scss
  src/services/service.ts
Labels: PR:Ready-to-Review
