Repository devtron-labs/dashboard, pull requests merged in 2023-10, with the labels that each got.

#1348 chore: shift common
  package.json
  src/components/AppSelector/ChartSelector.tsx
  src/components/ApplicationGroup/AppGroupDetailsRoute.tsx
  src/components/ApplicationGroup/Details/EnvCDDetails/EnvCDDetails.tsx
  src/components/ApplicationGroup/Details/EnvCIDetails/EnvCIDetails.tsx
  src/components/ApplicationGroup/Details/EnvironmentConfig/EnvConfig.tsx
  src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
  src/components/ApplicationGroup/List/EnvironmentListView.tsx
  src/components/ApplicationGroup/List/EnvironmentsList.tsx
  src/components/ClusterNodes/NodeDetails.tsx
  src/components/CodeEditor/CodeEditor.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/Jobs/JobList/JobsList.tsx
  src/components/apiTokens/EditAPIToken.tsx
  src/components/apiTokens/GenerateModal.tsx
  src/components/app/EventsLogs.tsx
  src/components/app/Overview/Overview.tsx
  src/components/app/ResourceTreeNodes.tsx
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/appDetails/AppMetrics.tsx
  src/components/app/details/cIDetails/CIDetails.tsx
  src/components/app/details/cdDetails/CDDetails.tsx
  src/components/app/details/cicdHistory/Artifacts.tsx
  src/components/app/details/testViewer/TestRunDetails.tsx
  src/components/app/details/testViewer/TestRunList.tsx
  src/components/app/list-new/AppList.tsx
  src/components/app/list/TriggerUrl.tsx
  src/components/chartRepo/ChartRepo.tsx
  src/components/charts/AdvancedConfig.tsx
  src/components/charts/ChartGroupDetails.tsx
  src/components/charts/list/ChartGroup.tsx
  src/components/ciConfig/CICreateDockerfileOption.tsx
  src/components/ciPipeline/ExternalCIPipeline.tsx
  src/components/ciPipeline/SourceMaterials.tsx
  src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
  src/components/cluster/ClusterForm.tsx
  src/components/cluster/ClusterInfoStepsModal.tsx
  src/components/common/ClipboardButton/ClipboardButton.tsx
  src/components/common/ClipboardButton/__tests__/ClipboardButton.test.tsx
  src/components/common/ClipboardButton/types.ts
  src/components/common/FloatingVariablesSuggestions/FloatingVariablesSuggestions.tsx
  src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx
  src/components/common/FloatingVariablesSuggestions/__tests__/FloatingVariablesSuggestions.test.tsx
  src/components/common/FloatingVariablesSuggestions/__tests__/SuggestionsItem.test.tsx
  src/components/common/helpers/Helpers.tsx
  src/components/common/index.ts
  src/components/common/navigation/NavigationRoutes.tsx
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/deploymentGroups/BulkActionDetails.tsx
  src/components/deploymentGroups/BulkActionEdit.tsx
  src/components/dockerRegistry/Docker.tsx
  src/components/gitProvider/GitProvider.tsx
  src/components/notifications/WebhookConfigModal.tsx
  src/components/scopedVariables/ScopedVariables.tsx
  src/components/scopedVariables/__tests__/ScopedVariables.test.tsx
  src/components/userGroups/UserGroup.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/CopyToast.tsx
  src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/EnvironmentStatus.component.tsx
  src/css/base.scss
Labels: PR:Ready-to-Review

#1349 fix: overridden CI workflow link breaking
  src/components/workflowEditor/Workflow.tsx
Labels: enhancement, PR:Ready-to-Review

#1351 Fix/node error in cluster
  src/components/CIPipelineN/Sidebar.tsx
  src/components/CIPipelineN/ciPipeline.utils.ts
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/ClusterNodes/ColumnSelector.tsx
  src/components/ClusterNodes/NodeDetails.tsx
  src/components/ClusterNodes/NodeDetailsList.tsx
  src/components/ClusterNodes/NodeListSearchFilter.tsx
  src/components/ClusterNodes/types.ts
  src/components/ResourceBrowser/Constants.ts
  src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/components/ResourceBrowser/ResourceList/Sidebar.tsx
  src/components/common/DynamicTabs/useTabs.ts
Labels: PR:Issue-verification-failed

#1336 fix: commit link not working, when git account is configured with ssh key
  src/components/common/helpers/git.ts
Labels: PR:Issue-verification-failed

#1353 fix: remove reptition of excluded blocks
  src/components/app/details/triggerView/cdMaterial.tsx
Labels: PR:Ready-to-Review

#1354 Fix: token cancel on filter
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/config/searchWorker.ts
Labels: PR:Issue-verification-failed

#1359 chore: revert default tooltip without word break
  src/components/scopedVariables/VariablesList.tsx
  src/css/base.scss
Labels: PR:Ready-to-Review

#1170 feat: Plugin input variables are not editable
  package.json
  src/components/CIPipelineN/CustomInputVariableSelect.tsx
  src/components/CIPipelineN/InputPluginSelect.tsx
  src/components/CIPipelineN/VariableContainer.tsx
  src/components/ConfigMapSecret/Types.ts
  src/components/app/types.ts
Labels: PR:Ready-to-Review

#1350 feat: add timer resource browser
  src/components/CIPipelineN/Sidebar.tsx
  src/components/CIPipelineN/ciPipeline.utils.ts
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/ClusterNodes/ClusterSelectionList.tsx
  src/components/ClusterNodes/ColumnSelector.tsx
  src/components/ClusterNodes/NodeDetails.tsx
  src/components/ClusterNodes/NodeDetailsList.tsx
  src/components/ClusterNodes/NodeListSearchFilter.tsx
  src/components/ClusterNodes/clusterNodes.scss
  src/components/ClusterNodes/types.ts
  src/components/ResourceBrowser/Constants.ts
  src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/components/ResourceBrowser/ResourceList/Sidebar.tsx
  src/components/app/list-new/AppList.tsx
  src/components/common/DynamicTabs/DynamicTabs.component.tsx
  src/components/common/DynamicTabs/DynamicTabs.tsx
  src/components/common/DynamicTabs/Types.ts
  src/components/common/DynamicTabs/useTabs.ts
  src/components/common/helpers/time.ts
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
  src/config/searchWorker.ts
Labels: PR:Ready-to-Review

#1358 fix: Deploy Chart CTA visibility on readme and compare values selection
  src/components/v2/values/chartValuesDiff/ChartValuesGUIView.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.scss
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesViewUtils.scss
Labels: PR:Ready-to-Review

#1327 fix: reload after deletion
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
Labels: PR:Issue-verification-failed

#1321 fix: no rows selected warning is coming on configure page of helm charts
  src/components/v2/appDetails/AppDetails.component.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
Labels: PR:Issue-verification-failed

#1256 feat: Abort controller in Config maps, Secrets and Deployment template
  src/components/ConfigMapSecret/ConfigMap/ConfigMapList.tsx
  src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
  src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
  src/components/ConfigMapSecret/service.ts
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/EnvironmentOverride/service.ts
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
  src/components/deploymentConfig/service.tsx
  src/services/service.ts
Labels: PR:Ready-to-Review

#1274 Cancellation token base template
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
  src/components/deploymentConfig/service.tsx
Labels: PR:Issue-verification-failed

#1365 fix: Environment dropdown is not opening until resource tree is not coming
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/appDetails/appDetails.type.ts
  src/components/app/service.ts
Labels: PR:Issue-verification-failed

#1370 chore: update fe-common version
  package.json
Labels: PR:Ready-to-Review

#1254 feat: deployment manifest
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/deploymentConfig/DeploymentConfig.utils.ts
  src/components/deploymentConfig/DeploymentConfigReducer.ts
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigToolbar.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateOptionsTab.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateView.component.tsx
  src/components/deploymentConfig/constants.tsx
  src/components/deploymentConfig/deploymentConfig.scss
  src/components/deploymentConfig/service.tsx
  src/components/deploymentConfig/types.tsx
  src/config/constants.ts
  src/css/base.scss
Labels: PR:Ready-to-Review

#1364 feat: listing all artifacts in case of ci-job type
  src/components/app/details/cIDetails/CIDetails.tsx
  src/components/app/details/cicdHistory/Artifacts.tsx
  src/components/app/details/cicdHistory/types.tsx
  src/components/app/service.ts
  src/components/app/types.ts
Labels: PR:Ready-to-Review

#1381 fix: refresh issue on add project & host url update and process undefined on dev server
  package.json
  src/components/common/formFields/ButtonWithLoader.tsx
  src/components/hostURL/HostURL.tsx
  src/components/project/Project.tsx
  src/components/userGroups/AppPermissions.tsx
  yarn.lock
Labels: PR:Ready-to-Review

#1384 fix: data persistence issue in env overrides
  src/components/EnvironmentOverride/EnvironmentOverride.tsx
Labels: PR:Ready-to-Review

#1387 fix: loading state in resource browser
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
Labels: PR:Ready-to-Review

#1386 fix: Bugathon DT-19 version-2 fixes
  src/components/ConfigMapSecret/ConfigMapSecret.reducer.ts
  src/components/ConfigMapSecret/ConfigMapSecretDataEditorContainer.tsx
  src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
  src/components/ConfigMapSecret/Types.ts
  src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
  src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/components/ResourceBrowser/Types.ts
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/common/GitInfoMaterial.tsx
  src/components/hostURL/HostURL.tsx
  src/components/login/SSOLogin.tsx
  src/components/userGroups/UserGroup.tsx
  src/util/DeleteComponent.tsx
Labels: PR:Ready-to-Review

#1382 fix(prod): input variable
  src/assets/icons/ic-var-initial.svg
  src/components/CIPipelineN/Constants.tsx
  src/components/CIPipelineN/CustomInputVariableSelect.tsx
  src/components/CIPipelineN/InputPluginSelect.tsx
  src/components/ConfigMapSecret/Types.ts
  src/components/app/types.ts
  src/css/base.scss
Labels: PR:Ready-to-Review

#1389 fix: wrong task name
  src/components/CIPipelineN/CustomInputVariableSelect.tsx
Labels: PR:Ready-to-Review

#1374 fix: updated redirection for ci-job type in Devtron Apps
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/CIPipelineN/CIPipeline.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/ciMaterial.tsx
  src/components/app/details/triggerView/types.ts
  src/components/app/details/triggerView/workflow.service.ts
  src/components/app/details/triggerView/workflow/Workflow.tsx
  src/components/ciConfig/CIConfigForm.tsx
  src/components/common/GitInfoMaterial.tsx
  src/components/common/helpers/workflowURL.ts
  src/components/workflowEditor/Workflow.tsx
  src/components/workflowEditor/workflowEditor.tsx
Labels: enhancement, PR:Issue-verification-failed

#1385 fix: pre/post CI/CD, Preset plugin input variable got invisible after adding as condition fix
  package.json
  src/components/CIPipelineN/ciPipeline.utils.ts
  src/components/EnvironmentOverride/EnvironmentOverride.tsx
  src/components/common/formFields/ButtonWithLoader.tsx
  src/components/hostURL/HostURL.tsx
  src/components/project/Project.tsx
  src/components/userGroups/AppPermissions.tsx
  yarn.lock
Labels: PR:Issue-verification-failed

#1377 fix: don't allow special chars in data vol in cm cs
  src/components/ConfigMapSecret/ConfigMapSecretForm.tsx
  src/components/cdPipeline/validationRules.ts
  src/config/constantMessaging.ts
  src/config/constants.ts
Labels: PR:Issue-verification-failed

#1393 fix: deploy button disabled in cd
  src/components/app/details/triggerView/cdMaterial.tsx
Labels: PR:Ready-to-Review

#1392 fix: App details page showing incorrect pod's details
  src/components/ConfigMapSecret/ConfigMap/ConfigMapList.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
Labels: PR:Ready-to-Review

#1391 fix: input var bugs
  src/components/CIPipelineN/CustomInputOutputVariables.tsx
Labels: PR:Ready-to-Review

#1395 fix:issue with service URL and port numbers
  src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
Labels: PR:Ready-to-Review

#1372 feat: floating widget & variable resolve
  src/assets/icons/ic-view-variables.svg
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
  src/components/EnvironmentOverride/environmentOverride.scss
  src/components/app/details/cdDetails/cd.type.ts
  src/components/app/details/cdDetails/cdDetail.scss
  src/components/app/details/cdDetails/deploymentHistoryDiff/DeploymentHistoryDiffView.tsx
  src/components/app/details/cdDetails/service.ts
  src/components/app/details/triggerView/triggerViewConfigDiff/TriggerViewConfigDiff.tsx
  src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx
  src/components/common/FloatingVariablesSuggestions/Suggestions.tsx
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/deploymentConfig/DeploymentConfigReducer.ts
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigToolbar.tsx
  src/components/deploymentConfig/deploymentConfig.scss
Labels: PR:Ready-to-Review

#1397 fix:2 pages are getting broken in this specific case of linked ci-pipeline
  src/components/CIPipelineN/CustomInputOutputVariables.tsx
  src/components/CIPipelineN/ciPipeline.utils.ts
  src/components/ClusterNodes/ColumnSelector.tsx
  src/components/ClusterNodes/NodeListSearchFilter.tsx
  src/components/ConfigMapSecret/ConfigMap/ConfigMapList.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/main.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
Labels: PR:Issue-verification-failed

#1399 feat:Creation of build pipeline
  .env
  src/components/CIPipelineN/CIPipeline.tsx
  src/index.tsx
Labels: PR:Ready-to-Review

#1378 feat: filter conditions modal
  package.json
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/CIPipelineN/CustomScript.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/assets/cdMaterialFooter.png
  src/components/app/details/triggerView/assets/configDiff.png
  src/components/app/details/triggerView/assets/configHeader.png
  src/components/app/details/triggerView/cdMaterial.readme.md
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/details/triggerView/types.ts
  src/components/app/service.ts
  src/components/ciPipeline/ciPipeline.scss
  src/css/base.scss
Labels: PR:Ready-to-Review

#1409 fix: Show excluded commits button hides if in case branch name is too long
  src/components/Jobs/ExpandedRow/ExpandedRow.scss
  src/components/ciPipeline/CiPipelineSourceConfig.tsx
  src/components/common/GitInfoMaterial.tsx
Labels: PR:Ready-to-Review

#1356 feat: Custom tag in Build CI and app group
  src/assets/icons/ic-generated-image.svg
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/CIPipelineN/AdvancedConfigOptions.tsx
  src/components/CIPipelineN/Build.tsx
  src/components/CIPipelineN/CIPipeline.tsx
  src/components/CIPipelineN/CustomImageTag.type.ts
  src/components/CIPipelineN/CustomImageTags.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/ciConfig/CIConfig.scss
  src/components/ciConfig/types.tsx
  src/components/ciPipeline/ciPipeline.scss
  src/components/ciPipeline/ciPipeline.service.ts
  src/components/ciPipeline/types.ts
  src/components/ciPipeline/validationRules.ts
  src/components/workflowEditor/types.ts
  src/config/constantMessaging.ts
  src/config/constants.ts
  src/css/base.scss
Labels: PR:Ready-to-Review

#1415 fix: CSS fix
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.scss
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/css/base.scss
Labels: PR:Ready-to-Review

#1403 feat: resolve scoped var deployment template
  src/assets/icons/ic-view-variable-toggle.svg
  src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/deploymentConfig/DeploymentConfigReducer.ts
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigToolbar.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateView.component.tsx
  src/components/deploymentConfig/constants.tsx
  src/components/deploymentConfig/deploymentConfig.scss
  src/components/deploymentConfig/types.tsx
  src/css/base.scss
Labels: PR:Ready-to-Review

#1414 feat: Custom tag v2
  src/components/CIPipelineN/AdvancedConfigOptions.tsx
  src/components/CIPipelineN/Build.tsx
  src/components/CIPipelineN/CIPipeline.tsx
  src/components/CIPipelineN/CustomImageTag.type.ts
  src/components/CIPipelineN/CustomImageTags.tsx
  src/components/CIPipelineN/ciPipeline.utils.ts
  src/components/cdPipeline/BuildCD.tsx
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/ciConfig/types.tsx
  src/components/ciPipeline/ciPipeline.scss
  src/components/ciPipeline/ciPipeline.service.ts
  src/components/ciPipeline/types.ts
  src/components/workflowEditor/types.ts
  src/css/base.scss
Labels: PR:Issue-verification-failed

#1412 feat: modify cluster overview
  src/assets/icons/cluster-overview.svg
  src/assets/icons/ic-world-black.svg
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/ClusterNodes/clusterNodes.service.tsx
  src/components/ClusterNodes/constants.ts
  src/components/ClusterNodes/types.ts
  src/components/ResourceBrowser/Constants.ts
  src/components/ResourceBrowser/ResourceList/ConnectingToClusterState.tsx
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
  src/components/ResourceBrowser/ResourceList/Sidebar.tsx
  src/components/ResourceBrowser/Utils.ts
  src/components/app/types.ts
  src/components/common/Description/GenericDescription.tsx
  src/components/common/DynamicTabs/useTabs.ts
  src/components/common/EditableTextArea/EditableTextArea.tsx
  src/components/v2/appDetails/appDetails.store.ts
  src/config/constants.ts
  src/css/base.scss
Labels: PR:Issue-verification-failed

#1286 fix: helm app list filter fixed and NOT DEPLOYED filter added in devtron apps
  src/components/app/config.tsx
  src/components/app/list-new/AppList.tsx
  src/components/app/list-new/HelmAppList.tsx
Labels: PR:Issue-verification-failed

#1427 docs: Create config.md to expose all the env variables
  config.md
Labels: PR:Ready-to-Review

#1430 fix: added null check
  src/components/cluster/Cluster.tsx
Labels: PR:Ready-to-Review
