Repository devtron-labs/dashboard, pull requests merged in 2024-04, with the labels that each got.

#1671 feat: add git hash column and sorting support in environment list table
  package.json
  src/Pages/Shared/CommitChipCell/CommitChipCell.tsx
  src/Pages/Shared/CommitChipCell/index.ts
  src/Pages/Shared/CommitChipCell/types.ts
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/Constants.ts
  src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/envOverview.scss
  src/components/app/Overview/EnvironmentList.tsx
  src/components/app/Overview/Overview.scss
  src/components/app/Overview/Overview.tsx
  src/components/app/Overview/constants.ts
  src/components/app/details/appDetails/DeployedCommitCard.tsx
  src/components/app/list/TriggerInfo.tsx
  src/components/app/service.ts
  src/services/service.types.ts
Labels: PR:Ready-to-Review

#1697 fix: security scan modal stop propagation
  src/components/common/security/ScanDetailsModal.tsx
  src/components/security/SecurityScansTab.tsx
Labels: PR:Issue-verification-failed

#1696 feat: add service worker timeout
  .env
  config.md
  src/App.tsx
  src/components/common/security/ScanDetailsModal.tsx
  src/index.tsx
Labels: PR:Issue-verification-failed

#1691 fix:- on select material page breaks on error
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/details/triggerView/TriggerView.tsx
Labels: PR:Ready-to-Review

#1702 fix: Dw qa files 2
  src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusRow.tsx
Labels: PR:Issue-verification-failed

#1690 fix: cancel token
  src/components/AppSelector/AppSelector.tsx
  src/components/AppSelector/AppSelectorUtil.tsx
  src/components/ApplicationGroup/AppGroup.service.ts
  src/components/ApplicationGroup/AppGroup.utils.ts
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/ApplicationGroup/EnvSelector.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/service.ts
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/cdPipeline/types.ts
  src/components/notifications/AddNotification.tsx
  src/components/workflowEditor/Workflow.tsx
  src/components/workflowEditor/nodes/CDNode.tsx
  src/components/workflowEditor/types.ts
  src/components/workflowEditor/workflowEditor.tsx
Labels: PR:Ready-to-Review

#1652 fix: clipboard button ui interaction
  .env
  config.md
  package.json
  src/App.tsx
  src/Pages/GlobalConfigurations/Authorization/APITokens/ApiTokens.component.tsx
  src/Pages/GlobalConfigurations/Authorization/APITokens/EditAPIToken.tsx
  src/Pages/GlobalConfigurations/Authorization/APITokens/GenerateModal.tsx
  src/Pages/GlobalConfigurations/Authorization/APITokens/apiToken.type.ts
  src/components/CIPipelineN/TaskTypeDetailComponent.tsx
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/ClusterNodes/NodeDetails.tsx
  src/components/CodeEditor/CodeEditor.tsx
  src/components/app/details/cicdHistory/Artifacts.tsx
  src/components/app/details/cicdHistory/History.components.tsx
  src/components/app/details/cicdHistory/types.tsx
  src/components/app/details/triggerView/Constants.ts
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/list/TriggerUrl.tsx
  src/components/ciConfig/CICreateDockerfileOption.tsx
  src/components/ciPipeline/ConfigureWebhook.tsx
  src/components/ciPipeline/SourceMaterials.tsx
  src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
  src/components/cluster/ClusterInfoStepsModal.tsx
  src/components/common/FloatingVariablesSuggestions/SuggestionItem.tsx
  src/components/common/security/ScanDetailsModal.tsx
  src/components/notifications/WebhookConfigModal.tsx
  src/components/security/SecurityScansTab.tsx
  src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/AppStatusDetailsChart.tsx
  src/config/constantMessaging.ts
  src/index.tsx
  yarn.lock
Labels: PR:Ready-to-Review

#1644 feat: Deployment window
  package.json
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusListDrawer.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusRow.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx
  src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.scss
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/Overview/Overview.tsx
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/appDetails/SourceInfo.tsx
  src/components/app/details/appDetails/appDetails.type.ts
  src/components/app/details/cIDetails/ciDetails.scss
  src/components/app/details/cdDetails/CDDetails.tsx
  src/components/app/details/cicdHistory/TriggerDetails.tsx
  src/components/app/details/cicdHistory/types.tsx
  src/components/app/details/triggerView/Constants.ts
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/details/triggerView/types.ts
  src/components/app/details/triggerView/workflow.service.ts
  src/components/app/details/triggerView/workflow/Workflow.tsx
  src/components/app/details/triggerView/workflow/nodes/triggerCDNode.tsx
  src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
  src/components/app/details/triggerView/workflow/nodes/triggerPrePostCDNode.tsx
  src/components/app/types.ts
  src/components/cdPipeline/DeleteCDNode.tsx
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/cdPipeline/cdpipeline.util.tsx
  src/components/v2/appDetails/NodeTreeDetailTab.tsx
  src/components/v2/appDetails/appDetails.type.ts
  src/components/v2/appDetails/k8Resource/K8Resource.component.tsx
  src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
  src/components/v2/appDetails/k8Resource/nodeType/NodeDelete.component.tsx
  src/components/v2/appDetails/sourceInfo/rotatePods/RotatePodsModal.component.tsx
  src/components/v2/appDetails/sourceInfo/rotatePods/rotatePodsModal.type.ts
  src/components/workflowEditor/Workflow.tsx
  src/components/workflowEditor/nodes/CDNode.tsx
  src/components/workflowEditor/types.ts
  src/css/base.scss
  src/css/formulae.scss
  src/css/icons.scss
  src/css/triggerView.scss
  src/services/service.types.ts
  yarn.lock
Labels: PR:Ready-to-Review

#1703 feat: image scan notification
  src/components/notifications/WebhookConfigModal.tsx
  src/components/notifications/notifications.service.ts
Labels: PR:Ready-to-Review

#1717 feat: hide GitOps repo
  .env
  package.json
  src/components/gitOps/GitOpsConfiguration.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.type.ts
  src/index.tsx
Labels: PR:Ready-to-Review

#1727 fixes: Css fixes for link app
  src/components/ClusterNodes/ClusterTerminal.tsx
  src/components/common/ClusterMetaDataBar/ClusterMetaData.scss
  src/components/common/ClusterMetaDataBar/ClusterMetaDataBar.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.type.ts
  src/css/base.scss
Labels: PR:Issue-verification-failed

#1718 feat: Integration of cluster terminal data in devtron apps & helm apps
  src/assets/icons/ic-resource.svg
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusRow.tsx
  src/components/ClusterNodes/ClusterTerminal.tsx
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/common/ClusterMetaDataBar/ClusterMetaData.scss
  src/components/common/ClusterMetaDataBar/ClusterMetaDataBar.tsx
  src/components/common/ClusterMetaDataBar/types.ts
  src/components/v2/appDetails/AppDetails.component.tsx
  src/components/v2/appDetails/k8Resource/K8Resource.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/Terminal.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.type.ts
  src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
  src/css/base.scss
Labels: enhancement, PR:Ready-to-Review

#1730 feat: added entry point for external argo apps
  src/components/app/list-new/AppList.tsx
  src/components/app/list-new/ExternalArgoList.tsx
  src/components/v2/appDetails/NodeTreeDetailTab.tsx
  src/components/v2/appDetails/appDetails.type.ts
  src/components/v2/appDetails/k8Resource/K8Resource.component.tsx
  src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
Labels: PR:Issue-verification-failed

#1725 chore: testid for resource browser
  src/components/ClusterNodes/NodeDetailsList.tsx
  src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
Labels: PR:Ready-to-Review

#1682 chore: extract infoicontippy component from tippycustomized
  .eslintignore
  package.json
  src/Pages/GlobalConfigurations/Authorization/APITokens/APITokenList.tsx
  src/Pages/GlobalConfigurations/Authorization/APITokens/CreateAPIToken.tsx
  src/Pages/GlobalConfigurations/Authorization/PermissionGroups/List/PermissionGroupListHeader.tsx
  src/Pages/GlobalConfigurations/Authorization/UserPermissions/List/UserPermissionListHeader.tsx
  src/components/CIPipelineN/DockerArgs.tsx
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/ClusterNodes/NodeActions/DrainNodeModal.tsx
  src/components/ConfigMapSecret/ConfigMap/ConfigMapList.tsx
  src/components/ConfigMapSecret/InfoIconWithTippy.tsx
  src/components/ConfigMapSecret/Secret/SecretList.tsx
  src/components/ConfigMapSecret/Types.ts
  src/components/CustomChart/CustomChartList.tsx
  src/components/app/EventsLogs.tsx
  src/components/app/details/appDetails/AppStatusCard.tsx
  src/components/app/details/appDetails/DeployedCommitCard.tsx
  src/components/app/details/appDetails/DeploymentStatusCard.tsx
  src/components/app/details/appDetails/DeploymentStatusDetailRow.tsx
  src/components/app/details/appDetails/IssuesCard.tsx
  src/components/app/details/appDetails/SecurityVulnerabilityCard.tsx
  src/components/app/details/cicdHistory/Artifacts.tsx
  src/components/app/details/cicdHistory/LogsRenderer.tsx
  src/components/app/details/metrics/DeploymentMetrics.tsx
  src/components/app/details/metrics/deploymentMetrics.util.tsx
  src/components/app/details/testViewer/TestRunDetails.tsx
  src/components/app/list-new/ExternalArgoList.tsx
  src/components/app/list-new/HelmAppList.tsx
  src/components/app/list/AppListView.tsx
  src/components/bulkEdits/BulkEdits.tsx
  src/components/cdPipeline/BuildCD.tsx
  src/components/cdPipeline/CDPipeline.tsx
  src/components/chartRepo/ChartRepo.tsx
  src/components/ciConfig/BuildContext.tsx
  src/components/ciConfig/CIBuildpackBuildOptions.tsx
  src/components/ciPipeline/Webhook/WebhookDetailsModal.tsx
  src/components/cluster/ClusterForm.tsx
  src/components/cluster/ClusterInstallStatus.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx
  src/components/dockerRegistry/Docker.tsx
  src/components/dockerRegistry/ManageRegistry.tsx
  src/components/externalLinks/ExternalLinks.tsx
  src/components/externalLinks/ExternalLinksCRUD/ConfigureLinkAction.tsx
  src/components/material/MaterialView.tsx
  src/components/notifications/SlackConfigModal.tsx
  src/components/scopedVariables/Descriptor.tsx
  src/components/security/Security.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/EphemeralContainerDrawer.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.utils.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/ChartUsedCard.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/CurrentSyncStatus.tsx
  src/components/v2/appDetails/sourceInfo/environmentStatus/HelmAppConfigApplyStatusCard.tsx
  src/components/v2/appDetails/sourceInfo/rotatePods/RotatePodsModal.component.tsx
  src/components/workflowEditor/workflowEditor.tsx
  src/config/constants.ts
  yarn.lock
Labels: PR:Ready-to-Review

#1709 fix: error page for all the error status code
  package.json
  src/Pages/GlobalConfigurations/Authorization/APITokens/ApiTokens.component.tsx
  src/components/ClusterNodes/ClusterOverview.tsx
  src/components/ClusterNodes/NodeDetails.tsx
  src/components/ClusterNodes/NodeDetailsList.tsx
  src/components/CustomChart/CustomChartList.tsx
  src/components/Jobs/JobList/JobListView.tsx
  src/components/Jobs/JobList/JobsList.tsx
  src/components/app/details/appDetails/appDetails.scss
  src/components/app/details/main.tsx
  src/components/app/details/metrics/DeploymentMetrics.tsx
  src/components/app/list-new/AppList.tsx
  src/components/app/list-new/HelmAppList.tsx
  src/components/app/list/AppListView.tsx
  src/components/charts/SavedValues/SavedValuesList.tsx
  src/components/charts/chartValues/ChartValues.tsx
  src/components/cluster/Cluster.tsx
  src/components/deploymentGroups/DeploymentGroupList.tsx
  src/components/externalLinks/ExternalLinks.tsx
  src/components/gitOps/GitOpsConfiguration.tsx
  src/components/material/MaterialList.tsx
  src/components/project/ProjectList.tsx
  src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
  src/components/v2/chartDeploymentHistory/DockerImageDetails.tsx
  src/components/v2/chartDeploymentHistory/chartDeploymentHistory.service.ts
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/css/base.scss
  yarn.lock
Labels: PR:Ready-to-Review

#1708 feat: retain manifest state on tab switch inside NodeDetails.component.tsx
  src/components/v2/appDetails/appDetails.type.ts
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts
  src/components/v2/utils/tabUtils/link.type.ts
  src/components/v2/utils/tabUtils/tab.json.ts
  src/components/v2/utils/tabUtils/useTab.ts
Labels: PR:Ready-to-Review
