Repository devtron-labs/dashboard, pull requests merged in 2024-06, with the labels that each got.

#1799 fix: search letters stack up on browser history
  e2e-tests/adminLogin.spec.ts
  e2e-tests/auth.setup.ts
  e2e-tests/example.spec.ts
  jest.config.js
  playwright.config.ts
  src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
  src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
  src/components/ResourceBrowser/Types.ts
  src/config/searchWorker.ts
  tests-examples/demo-todo-app.spec.ts
  types/patternfly-react.d.ts
Labels: PR:Ready-to-Review

#1801 chore: remove obsolete call from Dockerfile
  Dockerfile
Labels: PR:Ready-to-Review

#1802 fix: Deployment window fix for hibernate
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx
Labels: PR:Ready-to-Review

#1808 chore: revert the search behaviour of resource browser search
  src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
  src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
  src/components/ResourceBrowser/Types.ts
  src/config/searchWorker.ts
Labels: PR:Ready-to-Review

#1805 fix: cdPipeline deletion causes error modal to close & doesn't open cluster not reachable modal
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/workflowEditor/nodes/CDNode.tsx
Labels: PR:Ready-to-Review

#1811 chore: sync namespace between url and state
  src/components/ResourceBrowser/ResourceList/ResourceFilterOptions.tsx
  src/components/ResourceBrowser/ResourceList/ResourceList.tsx
Labels: PR:Ready-to-Review

#1814 fix: send appId, envId to ConfigToolbar and DeploymentTemplateLockedDiff
  src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
  src/components/app/EventsLogs.tsx
  src/components/app/details/appDetails/appDetails.scss
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/TerminalWrapper.component.tsx
Labels: PR:Ready-to-Review

#1757 chore: replace getLoginInfo with useUserEmail
  package.json
  src/App.tsx
  src/components/ConfigMapSecret/ConfigMapSecret.components.tsx
  src/components/common/helpers/Helpers.tsx
  src/components/common/navigation/Navigation.tsx
  src/components/common/navigation/NavigationRoutes.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx
  src/components/login/Login.tsx
  src/components/login/login.types.ts
  src/index.tsx
  src/services/service.ts
  yarn.lock
Labels: PR:Ready-to-Review

#1804 feat: bitbucket dc
  .env
  package.json
  src/components/gitOps/GitOpsConfiguration.tsx
  src/components/gitOps/constants.ts
  src/components/gitOps/gitops.type.ts
  src/components/gitOps/utils.ts
  src/css/base.scss
  src/index.tsx
  yarn.lock
Labels: PR:Issue-verification-failed

#1810 feat: remove dead files (Deployment Group, CDPipeline)
  .eslintignore
  package.json
  src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/SSOLogin.component.tsx
  src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/constants.ts
  src/components/app/details/triggerView/types.ts
  src/components/cdPipeline/CDPipeline.tsx
  src/components/cdPipeline/NewCDPipeline.tsx
  src/components/cdPipeline/cdPipeline.types.ts
  src/components/cdPipeline/sampleConfig.json
  src/components/cdPipeline/types.ts
  src/components/ciPipeline/SourceMaterials.tsx
  src/components/common/eaEmptyState/EAEmptyState.tsx
  src/components/common/navigation/Navigation.tsx
  src/components/common/navigation/NavigationRoutes.tsx
  src/components/deploymentGroups/BulkActionDetails.tsx
  src/components/deploymentGroups/BulkActionEdit.tsx
  src/components/deploymentGroups/BulkActions.scss
  src/components/deploymentGroups/BulkActions.tsx
  src/components/deploymentGroups/DeploymentGroupList.tsx
  src/components/deploymentGroups/service.ts
  src/components/login/constants.ts
  src/components/v2/appDetails/k8Resource/nodeDetail/EphemeralContainerDrawer.tsx
  src/components/workflowEditor/workflowEditor.tsx
  src/config/constantMessaging.ts
  src/config/constants.ts
  src/config/routes.ts
  src/index.tsx
  yarn.lock
Labels: PR:Ready-to-Review

#1823 feat: add organization name
  .env
  config.md
  index.html
  package.json
  src/Pages/Shared/OrganizationFrame/OrganizationFrame.component.tsx
  src/Pages/Shared/OrganizationFrame/OrganizationTextLogo.tsx
  src/Pages/Shared/OrganizationFrame/index.ts
  src/Pages/Shared/index.ts
  src/assets/icons/ic-devtron-blue-outline.svg
  src/components/common/navigation/Navigation.tsx
  src/index.tsx
  yarn.lock
Labels: PR:Ready-to-Review

#1826 feat: Docker - repo list input convert to tags
  src/components/dockerRegistry/Docker.tsx
  src/components/dockerRegistry/creatableStyles.ts
Labels: PR:Ready-to-Review

#1829 feat: releases & tenants v3.2
  package.json
  src/assets/icons/git/docker.svg
  yarn.lock
Labels: PR:Ready-to-Review

#1825 feat: multi select namespace on k8s resource user permission
  src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/AppPermissions.component.tsx
  src/Pages/GlobalConfigurations/Authorization/Shared/components/K8sObjectPermissions/K8sListItemCard.tsx
  src/Pages/GlobalConfigurations/Authorization/Shared/components/K8sObjectPermissions/K8sPermissionModal.tsx
  src/Pages/GlobalConfigurations/Authorization/Shared/components/K8sObjectPermissions/K8sPermissionRow.tsx
  src/Pages/GlobalConfigurations/Authorization/Shared/components/K8sObjectPermissions/constants.ts
  src/Pages/GlobalConfigurations/Authorization/Shared/components/K8sObjectPermissions/utils.tsx
  src/Pages/GlobalConfigurations/Authorization/types.ts
  src/Pages/GlobalConfigurations/Authorization/utils.ts
  src/components/v2/common/ReactSelect.utils.tsx
Labels: PR:Ready-to-Review

#1800 feat: gui schema driven basic view on deployment template & env override view
  package.json
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
  src/components/EnvironmentOverride/service.ts
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/deploymentConfig/DeploymentConfig.utils.ts
  src/components/deploymentConfig/DeploymentConfigReducer.ts
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigFormCTA.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentConfigToolbar.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateEditorView.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateGUIView.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateOptionsTab.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateReadOnlyEditorView.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateView.component.tsx
  src/components/deploymentConfig/basicViewSchema.json
  src/components/deploymentConfig/constants.tsx
  src/components/deploymentConfig/deploymentConfig.scss
  src/components/deploymentConfig/service.tsx
  src/components/deploymentConfig/types.tsx
  src/components/deploymentConfig/utils.tsx
  src/components/deploymentConfig/validationRules.ts
  yarn.lock
Labels: PR:Ready-to-Review

#1835 fix: pod restart rbac
  src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.api.ts
  src/components/v2/appDetails/k8Resource/nodeType/Node.component.tsx
Labels: PR:Ready-to-Review

#1833 chore: update fe-common to support iframe container
  package.json
  yarn.lock
Labels: PR:Ready-to-Review

#1840 fix: ArgoCD authorisation
  src/assets/icons/ic-argocd-app.svg
  src/components/app/list-new/AppList.tsx
  src/components/app/list-new/ExternalArgoList.tsx
Labels: PR:Issue-verification-failed

#1832 fix: group chart deployment toast message
  .eslintignore
  src/components/charts/ChartGroupAdvanceDeploy.tsx
  src/components/charts/ChartGroupDetails.tsx
  src/components/charts/charts.helper.ts
  src/components/charts/charts.types.tsx
  src/components/charts/charts.util.tsx
Labels: bug, PR:Ready-to-Review

#1848 feat: chart repo
  src/components/app/list/list.scss
  src/components/chartRepo/ChartRepo.tsx
Labels: PR:Issue-verification-failed

#1851 chore: hotfix 12 to main
  src/assets/icons/ic-argocd-app.svg
  src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverride.tsx
  src/components/EnvironmentOverride/DeploymentTemplateOverrideForm.tsx
  src/components/EnvironmentOverride/service.ts
  src/components/app/list-new/AppList.tsx
  src/components/app/list-new/ExternalArgoList.tsx
  src/components/app/list/list.scss
  src/components/chartRepo/ChartRepo.tsx
  src/components/deploymentConfig/DeploymentConfig.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateGUIView.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateOptionsTab.tsx
  src/components/deploymentConfig/DeploymentTemplateView/DeploymentTemplateReadOnlyEditorView.tsx
  src/components/deploymentConfig/constants.tsx
  src/components/deploymentConfig/fallbackJobsNCronJobGuiSchema.json
  src/components/deploymentConfig/service.tsx
  src/components/deploymentConfig/utils.tsx
Labels: PR:Ready-to-Review

#1785 feat: add prompt on redirection for bulk actions
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateStatusListDrawer.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/RestartWorkloadModal.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/UnhibernateModal.tsx
  src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/details/triggerView/BranchRegexModal.tsx
  src/components/app/details/triggerView/CIMaterialModal.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/TriggerView.utils.tsx
  src/components/app/details/triggerView/cdMaterial.tsx
  src/components/app/details/triggerView/ciMaterial.tsx
  src/components/app/details/triggerView/types.ts
  src/components/app/service.ts
  src/components/charts/charts.service.ts
  src/components/charts/list/DiscoverCharts.tsx
  src/components/charts/modal/ChartGroupBasicDeploy.tsx
  src/components/external-apps/ExternalAppService.ts
  src/components/v2/chartDeploymentHistory/ChartDeploymentHistory.component.tsx
  src/components/v2/chartDeploymentHistory/RollbackConfirmationDialog.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.reducer.ts
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.type.ts
  src/components/v2/values/chartValuesDiff/constant.ts
  src/components/v2/values/common/chartValues.api.ts
  src/config/constants.ts
  src/config/routes.ts
Labels: PR:Ready-to-Review

#1830 fix: resource tree tabs - hides when scroll to page bottom fix
  src/components/v2/appDetails/k8Resource/K8Resource.component.tsx
  src/components/v2/appDetails/k8Resource/NodeTreeTabList.scss
  src/components/v2/appDetails/k8Resource/NodeTreeTabList.tsx
  src/components/v2/appDetails/k8Resource/k8resources.scss
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Events.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/EventsTable.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.scss
  src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.css
  src/components/v2/common/message.ui.tsx
Labels: bug, PR:Ready-to-Review

#1856 fix: retain ci modal on refresh
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/config/constants.ts
Labels: PR:Issue-verification-failed

#1834 feat: Resource Browser: Add sorting functionality to K8sResourcesList Table
  .eslintignore
  src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
  src/components/ResourceBrowser/Utils.tsx
  src/config/searchWorker.ts
Labels: enhancement, PR:Ready-to-Review

#1857 chore: retain ci modal on refresh
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/config/constants.ts
Labels: PR:Ready-to-Review

#1798 feat: move api queueing to common and add clone pipeline in app group
  package.json
  src/components/ApplicationGroup/AppGroup.service.ts
  src/components/ApplicationGroup/AppGroup.types.ts
  src/components/ApplicationGroup/AppGroupRoute.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/HibernateModal.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/RestartWorkloadModal.tsx
  src/components/ApplicationGroup/Details/EnvironmentOverview/service.ts
  src/components/ApplicationGroup/Details/TriggerView/BulkCDTrigger.tsx
  src/components/ApplicationGroup/Details/TriggerView/BulkCITrigger.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/service.ts
  src/css/base.scss
  yarn.lock
Labels: PR:Ready-to-Review

#1756 chore: added some data-test-id and some classNamePrefix
  src/Pages/GlobalConfigurations/Authorization/Shared/components/AppPermissions/DirectPermission.tsx
  src/Pages/GlobalConfigurations/Authorization/Shared/components/K8sObjectPermissions/K8sListItemCard.tsx
Labels: PR:Ready-to-Review

#1854 feat: resource browser sorting fix: k8resource list scroll bug
  .eslintignore
  src/components/ResourceBrowser/ResourceList/K8SResourceList.tsx
  src/components/ResourceBrowser/Utils.tsx
  src/components/v2/appDetails/k8Resource/K8Resource.component.tsx
  src/components/v2/appDetails/k8Resource/NodeTreeTabList.scss
  src/components/v2/appDetails/k8Resource/NodeTreeTabList.tsx
  src/components/v2/appDetails/k8Resource/k8resources.scss
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetail.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Events.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/EventsTable.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Logs.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/Manifest.component.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/nodeDetailTab.scss
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/terminal/terminal.scss
  src/components/v2/appDetails/k8Resource/nodeDetail/nodeDetail.css
  src/components/v2/common/message.ui.tsx
  src/config/searchWorker.ts
Labels: PR:Ready-to-Review

#1860 chore: update documentation versioning
  package.json
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/dockerRegistry/ManageRegistry.tsx
  src/components/v2/devtronStackManager/DevtronStackManager.component.tsx
  src/config/constants.ts
  yarn.lock
Labels: PR:Ready-to-Review

#1841 feat: release dashboard v4
  Dockerfile
  nginx-default.conf
  package.json
  src/Pages/Shared/CommitChipCell/CommitChipCell.tsx
  src/Pages/Shared/CommitChipCell/index.ts
  src/Pages/Shared/CommitChipCell/types.ts
  src/Pages/Shared/index.ts
  src/assets/icons/ic-devtron-blue-outline.svg
  src/components/ApplicationGroup/AppGroup.utils.ts
  src/components/ApplicationGroup/Details/EnvironmentOverview/EnvironmentOverview.tsx
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/app/Overview/EnvironmentList.tsx
  src/components/app/details/appDetails/AppDetails.tsx
  src/components/app/details/appDetails/DeployedCommitCard.tsx
  src/components/app/details/triggerView/MaterialHistory.tsx
  src/components/app/details/triggerView/MaterialSource.tsx
  src/components/app/details/triggerView/TriggerView.tsx
  src/components/app/details/triggerView/types.ts
  src/components/app/details/triggerView/workflow/nodes/triggerCINode.tsx
  src/components/app/list/TriggerInfo.tsx
  src/components/app/service.ts
  src/components/common/GitInfoMaterial.tsx
  src/components/common/helpers/git.ts
  src/components/common/helpers/time.ts
  src/components/common/index.ts
  src/components/common/navigation/Navigation.tsx
  src/components/dockerRegistry/creatableStyles.ts
  src/config/constants.ts
  src/css/base.scss
  src/css/triggerView.scss
  yarn.lock
Labels: PR:Ready-to-Review

#1859 chore: dirty state check for update and deploy helm app
  src/components/ApplicationGroup/Details/TriggerView/EnvTriggerView.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/components/v2/values/common/chartValues.api.ts
Labels: PR:Ready-to-Review

#1776 feat: add handling for ssh authMode
  .env
  .eslintignore
  package.json
  src/Pages/GlobalConfigurations/Authorization/SSOLoginServices/SSOLogin.component.tsx
  src/assets/icons/ic-aws-codecommit.svg
  src/components/cluster/Cluster.tsx
  src/components/cluster/ClusterForm.tsx
  src/components/common/helpers/Helpers.tsx
  src/components/dockerRegistry/Docker.tsx
  src/components/gitOps/GitOpsConfiguration.tsx
  src/components/gitOps/GitProviderTabIcons.tsx
  src/components/gitOps/UpdateConfirmationDialog.tsx
  src/components/gitOps/UserGitRepConfiguration.tsx
  src/components/gitOps/UserGitRepo.tsx
  src/components/gitOps/constants.ts
  src/components/gitOps/gitops.type.ts
  src/components/gitOps/utils.ts
  src/components/gitProvider/GitProvider.tsx
  src/components/material/CreateMaterial.tsx
  src/components/material/MaterialView.tsx
  src/components/material/UpdateMaterial.tsx
  src/components/material/material.types.ts
  src/components/scopedVariables/utils.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.component.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.reducer.ts
  src/components/v2/values/chartValuesDiff/ChartValuesView.tsx
  src/components/v2/values/chartValuesDiff/ChartValuesView.type.ts
  src/config/constants.ts
  src/css/base.scss
  src/custom.d.ts
  src/index.tsx
  src/services/service.ts
  yarn.lock
Labels: PR:Ready-to-Review

#1729 feat: Global config > Deployment window
  package.json
  src/components/common/DatePickers/Calender.tsx
  src/components/common/DatePickers/DayPickerRangeController.tsx
  src/components/globalConfigurations/GlobalConfiguration.tsx
  src/components/v2/appDetails/k8Resource/nodeDetail/NodeDetailTabs/CustomLogsModal/CustomLogsModal.tsx
  src/components/v2/common/ReactSelect.utils.tsx
  src/components/v2/common/ReactSelectCustomization.tsx
  src/config/routes.ts
  src/css/base.scss
  src/css/formulae.scss
  yarn.lock
Labels: PR:Ready-to-Review
